#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CamelBones-AppKit
version:      1.1.2
version_from: 
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
